### ISSUE TITLE
Icarus import path differs from higan

### ISSUE THREAD

**Issue by victordg-github** [byuu/higan#18]
Hi byuu,

First I'd like to thank you for all your work on emulation and specially on SNES preservation, it's truly admirable. And I completely agree with your approach on Game Packs instead of just bare roms, it just makes so much sense, I wish it was considered by more developers.

I'm using Higan on Linux, compiled from the latest source, and I noticed there's an inconsistency on the paths. I tested on a clean setup, creating a new system, then in the Cartridge section the default path is ~/higan/[System]/Cartridge. However when importing, Icarus creates the game pack in ~/Emulation/[System]. Just pointing the Higan cartridge folder to ~/Emulation/[System] is enough, but I think it can be quite confusing to new users. Higan is complicated enough for the average user which is a pity considering the quality of the software.

I tried to find the relevant source code to change the default path in Icarus but I'm not familiar with the source and I couldn't find it, I hope adjusting this is not so much trouble for you :)

Thanks in advance!

**Comment by victordg-github** [comment]
Sorry for the spam, I think I found the right source and I patched for myself, I hope it's valid as a general case. I don't use github often but I hope I didn't cause any trouble.

**Comment by byuu** [comment]
Hi, I appreciate the interest and support, but this one's a really complicated issue ^-^;;

The idea is that I don't want higan to differentiate between "things you plug into systems." For instance, the Super Turbo File holds its own save RAM memory despite being a "controller." Then there's memory cards, etc. Yet it would not make any sense for higan to import gamepads into a library. icarus exists as a necessity to convert game images into sensible formats. But the goal is to keep higan and icarus as separated as I can, so they don't share the same configuration file for paths and things, so that, hypothetically, icarus could be used as a separate project to higan.

So the reason higan defaults to ~/higan/<system name>/<media name> is because it's the same way controllers, expansion/extension port devices, etc work.

But then with icarus, it doesn't know about your higan systems you created. And you may have created multiple systems.

I agree and understand that it's a right pain to have to change the paths every time a new system is created to share games. I have been racking my brain trying to come up with something both consistent and user-friendly, but so far nothing has come to mind here =(

This specific issue is one of the *major* blockers for higan v107, for what it's worth.

**Comment by victordg-github** [comment]
Thanks for taking the time to explain in so much detail, it is quite clear now :)
If I may suggest, even just as an intermediate solution, I think it would be nice if at least Icarus would considered Higan's cartridge path only when invoked directly from the cartridge's import button, I believe that's what a normal user would expect. However like you say, Icarus is meant to be a separate project and not dependable on Higan so it should keep its own configuration/paths.

A long term solution is not simple giving Higan's design, but I'm confident your brilliant mind will come up with something eventually, your work is always worth the wait :)

**Comment by byuu** [comment]
I made this a bit nicer, it'll default to the icarus path on a new system if it exists (~/Emulation/System Name), otherwise it goes to a local path. Still need to update the icarus import button to target the active directory, but all in due time.

**Comment by victordg-github** [comment]
That's a nice solution, thanks Byuu! ^-^
