### ISSUE TITLE
[GB] Chiki Chiki Machine Mou Race (Japan) missing hud and bottom part of screen

### ISSUE THREAD

**Issue by benderscruffy** [byuu/higan#37]
using higan v106
missing hud in bottom right hand corner and bottom part of screen
![chiki](https://user-images.githubusercontent.com/2696404/64075205-eb609d80-cce7-11e9-9c0f-316a538f1945.PNG)

**Comment by byuu** [comment]
I appreciate the bug reports! But just a fair warning, the Game Boy and Game Boy Color cores have undergone massive emulation improvements since v106 was released. The nightlies are too difficult to recommend you to use them, however.

But I would say, it'd probably be best to stick to other systems for bug reports for now. There's a very good chance lots of these are already fixed, and also there may be new bugs that get missed by targeting v106.

In any case, thanks a lot for your time and testing!

**Comment by benderscruffy** [comment]
works fine in v106.208

**Comment by benderscruffy** [comment]
thanks  for that
i have no problems using the nightlies so i have retested the games
did you want me to keep testing higan or are you concentrating on bsnes and not worrying about the bugs in higan for a while

**Comment by byuu** [comment]
I don't really believe that the GitHub issue tracker is the best way to track individual game bugs, and it creates noise against more pressing issues. But I do believe in having the list of bugs publicly known *somehow*, and currently this is the only option we have. So in light of that, please feel free to continue. Thank you for your testing work!

And yes, I'm afraid non-SNES games have historically always been lower-priority. I've wanted to team up with another developer for over a decade, maybe one day it'll actually happen and more serious efforts can go into other systems too. But for one guy, it's too many systems to refine them to the level the SNES has been. There just isn't enough time.

**Comment by benderscruffy** [comment]
ok thanks for that
i will give up on testing as i dont wont to clutter up the board and have bugs sitting there for maybe years who knows 
see what happens in the future
